package com.tmt.automation.controller;

import com.tmt.automation.model.RunTestCase;
import com.tmt.automation.model.RunTestCaseResult;
import com.tmt.automation.repository.RunTestCaseResultRepository;
import com.tmt.automation.service.TestExecutorService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/api/runtestcase")
public class RunTestCaseController {

    @Autowired
    private TestExecutorService testExecutorService;

    @Autowired
    private RunTestCaseResultRepository runTestCaseResultRepository;

    @PostMapping
    public ResponseEntity<?> runTestCases(@RequestBody RunTestCase request) {
        if (request.getTestCaseIds() == null || request.getTestCaseIds().isEmpty()) {
            return ResponseEntity.badRequest().body("No testCaseIds provided.");
        }

        // Generate a runId if not set
        String runId = request.getRunId();
        if (runId == null || runId.isEmpty()) {
            runId = "N-" + System.currentTimeMillis();
            request.setRunId(runId);
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yy, HH-mm");

        List<RunTestCaseResult> resultList = new ArrayList<>();

        for (String testCaseId : request.getTestCaseIds()) {
            boolean result = testExecutorService.executeTestCase(testCaseId);
            String status = result ? "PASS" : "FAIL";

            String currentDateTime = LocalDateTime.now().format(formatter);

            // Save each result in MongoDB with formatted date/time
            RunTestCaseResult dbResult = new RunTestCaseResult(
                null, // id will be auto-generated by MongoDB
                request.getProjectId(),
                request.getReleaseId(),
                runId,
                testCaseId,
                status,
                currentDateTime // formatted as DD-MM-YY, HH-MM
            );
            runTestCaseResultRepository.save(dbResult);
            resultList.add(dbResult);
        }

        return ResponseEntity.ok(resultList);
    }
}