package com.tmt.automation.model;

public enum BrowserAction {
    OPEN_BROWSER, CLOSE_BROWSER, ENTER_URL,ENTER_TEXT,
    WAIT,VERIFYTEXT,
    IMPLICITLYWAIT, EXPLICITWAIT, ISDISPLAYED, CLICK_WEB_ELEMENT, NAVIGATION_TO, NAVIGATE_BACK, NAVIGATE_FORWARD,
    NAVIGATE_REFRESH, RIGHT_CLICK, DOUBLE_CLICK, SELECTBYVISIBILETEXT,
    SELECTBYVALUE, SELECTBYINDEX, ALERT_WITH_OK, ALERT_CONFIRMBOX_WITH_OK,
    ALERT_CONFIRMBOX_WITH_CANCEL, MOUSE_HOVER, MOUSE_HOVER_CLICK,
    DRAG, DROP, FRAME, WINDOW_HANDLES_TO_CHILD, SCREENSHOT,
    ELEMENT_SCREENSHOT
}